### ISSUE TITLE
AppClassLoader cannot be cast to class java.net.URLClassLoader

### ISSUE THREAD

**Issue by Spongman** [FTBTeam/FTB-Sky-Adventures#295]
* **Modpack Version**: 1.4.0

* **Issue**: 

````
$ cat /etc/debian_version
9.8
$ java --version
java 12 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
$ ./ServerStart.sh
Missing eula.txt. Startup will fail and eula.txt will be created
Make sure to read eula.txt before playing!
To continue press <enter>

Starting server
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
````

**Comment by eri451** [comment]
I have this problem as well with other FTB packs using java v11 and java v14

<pre>
Params:
  --username  --version MultiMC5 --gameDir /home/user/.local/share/multimc/instances/FTB Presents Direwolf20 1.12/.minecraft --assetsDir /home/user/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx12000m, -Duser.language=en]


Minecraft process ID: 66612


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
Exiting with -1
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.
</pre>

**Comment by eri451** [comment]
I found some documentation on which java version should be used: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
That helped me, especially with FTB Packs.
The article basically states that java 8 should be used.
So @Spongman in your case (on debian stretch (9.8) or sid) maybe you could just
<code>sudo apt install openjdk-8-jre</code>

https://packages.debian.org/sid/openjdk-8-jre

**Comment by 016Nojr** [comment]
Try with Java 8
