### ISSUE TITLE
Sever lockup - on recovering 18,000 lines of .concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [FTBTeam/FTB-Sky-Adventures#72]
https://gist.github.com/ProsperCraft/7fe3312cdd9632ea4e9340164937937f

[15:50:56] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException

Full logs- 
[2018-10-20-7.log.gz](https://github.com/FTBTeam/FTB-Sky-Adventures/files/2498773/2018-10-20-7.log.gz)

**Comment by tfox83** [comment]
This has now been cleaned up
